[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps =
  bblanchon/ArduinoJson@^7.2.1
  knolleary/PubSubClient@^2.8
  adafruit/Adafruit SHT31 Library@^2.2.2
  milesburton/DallasTemperature@^3.11.0
  paulstoffregen/OneWire@^2.3.8
build_flags =
  -D GV_FIRMWARE_VERSION=\"0.1.0\"
