FROM python:3.12-slim
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
WORKDIR /app
COPY requirements.deploy.txt .
RUN pip install --no-cache-dir -r requirements.deploy.txt
COPY . .
EXPOSE 8010
CMD ["python", "start.py"]
