"""
Risk Engine v1 - Rule-Based Risk Assessment

The transport accepts GeoVision's six public sectors. Explicit rule packs are
currently implemented for Mining and Construction & Infrastructure; other
sectors remain visibly unconfigured instead of being relabelled as one of them.

Output:
- risk_score: 0-100 (0=lowest risk, 100=highest)
- risk_level: low/medium/high/critical
- triggers: List of triggered rules
- alerts: Generated alerts for dashboard
- recommendations: Suggested actions
"""

import logging
import math
from datetime import datetime
from typing import Optional, List, Dict, Any
from enum import Enum
from dataclasses import dataclass, field
from pydantic import BaseModel

from app.core.time import utc_now
from app.sector_taxonomy import normalize_public_sector

logger = logging.getLogger(__name__)


# ============ ENUMS & TYPES ============


class RiskLevel(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class AlertSeverity(str, Enum):
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"


class SectorType(str, Enum):
    AGRICULTURE = "agriculture"
    CONSTRUCTION_INFRASTRUCTURE = "construction_infrastructure"
    ENVIRONMENT = "environment"
    MINING = "mining"
    INDUSTRY_ENERGY_UTILITIES = "industry_energy_utilities"
    PORTS_LOGISTICS = "ports_logistics"

    @classmethod
    def _missing_(cls, value: object):
        canonical = normalize_public_sector(str(value))
        return cls._value2member_map_.get(canonical)


class RiskEngineNotConfiguredError(RuntimeError):
    """Raised when no evidence-backed rule pack exists for a public sector."""


class RiskEvidenceError(ValueError):
    """Raised when a configured rule pack lacks valid source measurements."""


RISK_RULE_THRESHOLDS = {
    SectorType.MINING: {
        "tailings_level_pct": {"warning": 80, "critical": 90, "unit": "%"},
        "terrain_displacement_mm": {
            "warning": 20,
            "critical": 50,
            "unit": "mm",
        },
        "esg_score": {
            "warning": 75,
            "critical": 60,
            "unit": "%",
            "inverse": True,
        },
        "dust_concentration_ppm": {
            "warning": 50,
            "critical": 100,
            "unit": "PPM",
        },
        "water_quality_index": {
            "warning": 70,
            "critical": 50,
            "unit": "index",
            "inverse": True,
        },
        "extraction_efficiency_pct": {
            "warning": 80,
            "critical": 70,
            "unit": "%",
            "inverse": True,
        },
    },
    SectorType.CONSTRUCTION_INFRASTRUCTURE: {
        "structural_health_index": {
            "warning": 80,
            "critical": 60,
            "unit": "index",
            "inverse": True,
        },
        "timeline_delay_days": {"warning": 7, "critical": 30, "unit": "days"},
        "budget_overrun_pct": {"warning": 10, "critical": 20, "unit": "%"},
        "safety_incidents_30d": {
            "warning": 1,
            "critical": 3,
            "unit": "count",
        },
        "material_quality_pass_rate": {
            "warning": 95,
            "critical": 90,
            "unit": "%",
            "inverse": True,
        },
    },
}


# ============ DATA CLASSES ============


@dataclass
class RuleResult:
    """Result from a single rule evaluation."""

    rule_id: str
    rule_name: str
    triggered: bool
    score_contribution: float  # Points added to risk score
    message: str
    severity: AlertSeverity
    data: Dict[str, Any] = field(default_factory=dict)


@dataclass
class RiskAlert:
    """Alert generated by risk assessment."""

    id: str
    title: str
    message: str
    severity: AlertSeverity
    sector: SectorType
    source: str
    metric_name: Optional[str] = None
    metric_value: Optional[float] = None
    threshold: Optional[float] = None
    recommendation: Optional[str] = None
    created_at: datetime = field(default_factory=utc_now)


@dataclass
class RiskAssessmentResult:
    """Complete risk assessment output."""

    assessment_id: str
    site_id: str
    sector: SectorType
    risk_score: float  # 0-100
    risk_level: RiskLevel
    triggered_rules: List[RuleResult]
    alerts: List[RiskAlert]
    recommendations: List[str]
    input_data: Dict[str, Any]
    assessed_at: datetime = field(default_factory=utc_now)


# ============ RULE DEFINITIONS ============


class RuleEngine:
    """Base class for sector-specific rule engines."""

    def __init__(self, sector: SectorType):
        self.sector = sector
        self.rules = []
        self.required_fields: tuple[str, ...] = ()

    def evaluate(self, data: Dict[str, Any]) -> List[RuleResult]:
        """Evaluate all rules against input data."""
        results = []
        for rule in self.rules:
            try:
                result = rule(data)
                results.append(result)
            except Exception as exc:
                logger.warning("Risk rule evaluation failed: %s", type(exc).__name__)
                raise RiskEvidenceError(
                    f"Risk rule '{rule.__name__}' could not evaluate supplied evidence"
                ) from exc
        return results


class MiningRuleEngine(RuleEngine):
    """Risk rules for mining operations."""

    def __init__(self):
        super().__init__(SectorType.MINING)
        self.required_fields = (
            "tailings_level_pct",
            "terrain_displacement_mm",
            "esg_score",
            "dust_concentration_ppm",
            "water_quality_index",
            "extraction_efficiency_pct",
        )
        self.rules = [
            self.rule_tailings_dam_level,
            self.rule_terrain_displacement,
            self.rule_esg_compliance,
            self.rule_dust_concentration,
            self.rule_water_quality,
            self.rule_extraction_efficiency,
        ]

    def rule_tailings_dam_level(self, data: Dict) -> RuleResult:
        """Check tailings dam fill level."""
        level = data.get("tailings_level_pct", 0)
        thresholds = RISK_RULE_THRESHOLDS[self.sector]["tailings_level_pct"]

        if level >= thresholds["critical"]:
            return RuleResult(
                rule_id="mining_tailings_90",
                rule_name="Tailings Dam Critical",
                triggered=True,
                score_contribution=40,
                message=f"Tailings dam at {level}% capacity - CRITICAL",
                severity=AlertSeverity.CRITICAL,
                data={"level": level, "threshold": thresholds["critical"]},
            )
        elif level >= thresholds["warning"]:
            return RuleResult(
                rule_id="mining_tailings_80",
                rule_name="Tailings Dam Warning",
                triggered=True,
                score_contribution=20,
                message=f"Tailings dam at {level}% capacity",
                severity=AlertSeverity.WARNING,
                data={"level": level, "threshold": thresholds["warning"]},
            )

        return RuleResult(
            rule_id="mining_tailings_ok",
            rule_name="Tailings Dam Level",
            triggered=False,
            score_contribution=0,
            message=f"Tailings dam at {level}% - OK",
            severity=AlertSeverity.INFO,
            data={"level": level},
        )

    def rule_terrain_displacement(self, data: Dict) -> RuleResult:
        """Check terrain/slope displacement from InSAR/LiDAR."""
        displacement_mm = data.get("terrain_displacement_mm", 0)
        thresholds = RISK_RULE_THRESHOLDS[self.sector]["terrain_displacement_mm"]

        if displacement_mm >= thresholds["critical"]:
            return RuleResult(
                rule_id="mining_displacement_50",
                rule_name="Terrain Displacement Critical",
                triggered=True,
                score_contribution=35,
                message=f"Terrain displacement {displacement_mm}mm detected - evacuation review needed",
                severity=AlertSeverity.CRITICAL,
                data={
                    "displacement": displacement_mm,
                    "threshold": thresholds["critical"],
                },
            )
        elif displacement_mm >= thresholds["warning"]:
            return RuleResult(
                rule_id="mining_displacement_20",
                rule_name="Terrain Displacement Warning",
                triggered=True,
                score_contribution=15,
                message=f"Terrain displacement {displacement_mm}mm - monitoring increased",
                severity=AlertSeverity.WARNING,
                data={
                    "displacement": displacement_mm,
                    "threshold": thresholds["warning"],
                },
            )

        return RuleResult(
            rule_id="mining_displacement_ok",
            rule_name="Terrain Stability",
            triggered=False,
            score_contribution=0,
            message="Terrain stable",
            severity=AlertSeverity.INFO,
            data={"displacement": displacement_mm},
        )

    def rule_esg_compliance(self, data: Dict) -> RuleResult:
        """Check ESG compliance score."""
        score = data.get("esg_score", 100)
        thresholds = RISK_RULE_THRESHOLDS[self.sector]["esg_score"]

        if score < thresholds["critical"]:
            return RuleResult(
                rule_id="mining_esg_low",
                rule_name="ESG Compliance Low",
                triggered=True,
                score_contribution=25,
                message=f"ESG compliance score {score}% - regulatory risk",
                severity=AlertSeverity.ERROR,
                data={"score": score, "threshold": thresholds["critical"]},
            )
        elif score < thresholds["warning"]:
            return RuleResult(
                rule_id="mining_esg_medium",
                rule_name="ESG Compliance Warning",
                triggered=True,
                score_contribution=10,
                message=f"ESG compliance score {score}% - improvement needed",
                severity=AlertSeverity.WARNING,
                data={"score": score, "threshold": thresholds["warning"]},
            )

        return RuleResult(
            rule_id="mining_esg_ok",
            rule_name="ESG Compliance",
            triggered=False,
            score_contribution=0,
            message=f"ESG score {score}%",
            severity=AlertSeverity.INFO,
            data={"score": score},
        )

    def rule_dust_concentration(self, data: Dict) -> RuleResult:
        """Check dust/particulate concentration."""
        dust_ppm = data.get("dust_concentration_ppm", 0)
        thresholds = RISK_RULE_THRESHOLDS[self.sector]["dust_concentration_ppm"]

        if dust_ppm >= thresholds["critical"]:
            return RuleResult(
                rule_id="mining_dust_high",
                rule_name="Dust Level Critical",
                triggered=True,
                score_contribution=20,
                message=f"Dust concentration {dust_ppm} PPM - health hazard",
                severity=AlertSeverity.ERROR,
                data={"dust": dust_ppm, "threshold": thresholds["critical"]},
            )
        if dust_ppm >= thresholds["warning"]:
            return RuleResult(
                rule_id="mining_dust_warning",
                rule_name="Dust Level Warning",
                triggered=True,
                score_contribution=10,
                message=f"Dust concentration {dust_ppm} PPM requires review",
                severity=AlertSeverity.WARNING,
                data={"dust": dust_ppm, "threshold": thresholds["warning"]},
            )

        return RuleResult(
            rule_id="mining_dust_ok",
            rule_name="Dust Level",
            triggered=False,
            score_contribution=0,
            message=f"Dust level {dust_ppm} PPM",
            severity=AlertSeverity.INFO,
            data={"dust": dust_ppm},
        )

    def rule_water_quality(self, data: Dict) -> RuleResult:
        """Check water quality index."""
        wqi = data.get("water_quality_index", 100)
        thresholds = RISK_RULE_THRESHOLDS[self.sector]["water_quality_index"]

        if wqi < thresholds["critical"]:
            return RuleResult(
                rule_id="mining_water_poor",
                rule_name="Water Quality Poor",
                triggered=True,
                score_contribution=20,
                message=f"Water quality index {wqi} - contamination risk",
                severity=AlertSeverity.ERROR,
                data={"wqi": wqi, "threshold": thresholds["critical"]},
            )
        if wqi < thresholds["warning"]:
            return RuleResult(
                rule_id="mining_water_warning",
                rule_name="Water Quality Warning",
                triggered=True,
                score_contribution=10,
                message=f"Water quality index {wqi} requires review",
                severity=AlertSeverity.WARNING,
                data={"wqi": wqi, "threshold": thresholds["warning"]},
            )

        return RuleResult(
            rule_id="mining_water_ok",
            rule_name="Water Quality",
            triggered=False,
            score_contribution=0,
            message=f"Water quality index {wqi}",
            severity=AlertSeverity.INFO,
            data={"wqi": wqi},
        )

    def rule_extraction_efficiency(self, data: Dict) -> RuleResult:
        """Check extraction efficiency."""
        efficiency = data.get("extraction_efficiency_pct", 100)
        thresholds = RISK_RULE_THRESHOLDS[self.sector]["extraction_efficiency_pct"]

        if efficiency < thresholds["critical"]:
            return RuleResult(
                rule_id="mining_efficiency_low",
                rule_name="Extraction Efficiency Low",
                triggered=True,
                score_contribution=10,
                message=f"Extraction efficiency {efficiency}% - below target",
                severity=AlertSeverity.ERROR,
                data={"efficiency": efficiency, "threshold": thresholds["critical"]},
            )
        if efficiency < thresholds["warning"]:
            return RuleResult(
                rule_id="mining_efficiency_warning",
                rule_name="Extraction Efficiency Warning",
                triggered=True,
                score_contribution=5,
                message=f"Extraction efficiency {efficiency}% requires review",
                severity=AlertSeverity.WARNING,
                data={"efficiency": efficiency, "threshold": thresholds["warning"]},
            )

        return RuleResult(
            rule_id="mining_efficiency_ok",
            rule_name="Extraction Efficiency",
            triggered=False,
            score_contribution=0,
            message=f"Efficiency {efficiency}%",
            severity=AlertSeverity.INFO,
            data={"efficiency": efficiency},
        )


class InfrastructureRuleEngine(RuleEngine):
    """Risk rules for infrastructure monitoring."""

    def __init__(self):
        super().__init__(SectorType.CONSTRUCTION_INFRASTRUCTURE)
        self.required_fields = (
            "structural_health_index",
            "timeline_delay_days",
            "budget_overrun_pct",
            "safety_incidents_30d",
            "material_quality_pass_rate",
        )
        self.rules = [
            self.rule_structural_health,
            self.rule_timeline_delay,
            self.rule_budget_overrun,
            self.rule_safety_incidents,
            self.rule_material_quality,
        ]

    def rule_structural_health(self, data: Dict) -> RuleResult:
        """Check structural health index from sensors/inspections."""
        shi = data.get("structural_health_index", 100)
        thresholds = RISK_RULE_THRESHOLDS[self.sector]["structural_health_index"]

        if shi < thresholds["critical"]:
            return RuleResult(
                rule_id="infra_structural_critical",
                rule_name="Structural Health Critical",
                triggered=True,
                score_contribution=40,
                message=f"Structural health index {shi} - immediate inspection required",
                severity=AlertSeverity.CRITICAL,
                data={"shi": shi, "threshold": thresholds["critical"]},
            )
        elif shi < thresholds["warning"]:
            return RuleResult(
                rule_id="infra_structural_warning",
                rule_name="Structural Health Warning",
                triggered=True,
                score_contribution=20,
                message=f"Structural health index {shi} - maintenance recommended",
                severity=AlertSeverity.WARNING,
                data={"shi": shi, "threshold": thresholds["warning"]},
            )

        return RuleResult(
            rule_id="infra_structural_ok",
            rule_name="Structural Health",
            triggered=False,
            score_contribution=0,
            message=f"Structural health index {shi}",
            severity=AlertSeverity.INFO,
            data={"shi": shi},
        )

    def rule_timeline_delay(self, data: Dict) -> RuleResult:
        """Check project timeline delay."""
        delay_days = data.get("timeline_delay_days", 0)
        thresholds = RISK_RULE_THRESHOLDS[self.sector]["timeline_delay_days"]

        if delay_days >= thresholds["critical"]:
            return RuleResult(
                rule_id="infra_delay_major",
                rule_name="Major Timeline Delay",
                triggered=True,
                score_contribution=25,
                message=f"Project {delay_days} days behind schedule",
                severity=AlertSeverity.ERROR,
                data={"delay": delay_days, "threshold": thresholds["critical"]},
            )
        elif delay_days >= thresholds["warning"]:
            return RuleResult(
                rule_id="infra_delay_minor",
                rule_name="Timeline Delay",
                triggered=True,
                score_contribution=10,
                message=f"Project {delay_days} days behind schedule",
                severity=AlertSeverity.WARNING,
                data={"delay": delay_days, "threshold": thresholds["warning"]},
            )

        return RuleResult(
            rule_id="infra_timeline_ok",
            rule_name="Timeline Status",
            triggered=False,
            score_contribution=0,
            message="Project on schedule",
            severity=AlertSeverity.INFO,
            data={"delay": delay_days},
        )

    def rule_budget_overrun(self, data: Dict) -> RuleResult:
        """Check budget overrun percentage."""
        overrun_pct = data.get("budget_overrun_pct", 0)
        thresholds = RISK_RULE_THRESHOLDS[self.sector]["budget_overrun_pct"]

        if overrun_pct >= thresholds["critical"]:
            return RuleResult(
                rule_id="infra_budget_critical",
                rule_name="Budget Overrun Critical",
                triggered=True,
                score_contribution=25,
                message=f"Budget overrun {overrun_pct}% - cost review needed",
                severity=AlertSeverity.ERROR,
                data={"overrun": overrun_pct, "threshold": thresholds["critical"]},
            )
        elif overrun_pct >= thresholds["warning"]:
            return RuleResult(
                rule_id="infra_budget_warning",
                rule_name="Budget Overrun",
                triggered=True,
                score_contribution=10,
                message=f"Budget overrun {overrun_pct}%",
                severity=AlertSeverity.WARNING,
                data={"overrun": overrun_pct, "threshold": thresholds["warning"]},
            )

        return RuleResult(
            rule_id="infra_budget_ok",
            rule_name="Budget Status",
            triggered=False,
            score_contribution=0,
            message="Budget on track",
            severity=AlertSeverity.INFO,
            data={"overrun": overrun_pct},
        )

    def rule_safety_incidents(self, data: Dict) -> RuleResult:
        """Check safety incident count."""
        incidents = data.get("safety_incidents_30d", 0)
        thresholds = RISK_RULE_THRESHOLDS[self.sector]["safety_incidents_30d"]

        if incidents >= thresholds["critical"]:
            return RuleResult(
                rule_id="infra_safety_high",
                rule_name="High Safety Incidents",
                triggered=True,
                score_contribution=30,
                message=f"{incidents} safety incidents in 30 days - safety review required",
                severity=AlertSeverity.ERROR,
                data={"incidents": incidents, "threshold": thresholds["critical"]},
            )
        elif incidents >= thresholds["warning"]:
            return RuleResult(
                rule_id="infra_safety_warning",
                rule_name="Safety Incident",
                triggered=True,
                score_contribution=15,
                message=f"{incidents} safety incident(s) in 30 days",
                severity=AlertSeverity.WARNING,
                data={"incidents": incidents, "threshold": thresholds["warning"]},
            )

        return RuleResult(
            rule_id="infra_safety_ok",
            rule_name="Safety Record",
            triggered=False,
            score_contribution=0,
            message="No safety incidents",
            severity=AlertSeverity.INFO,
            data={"incidents": incidents},
        )

    def rule_material_quality(self, data: Dict) -> RuleResult:
        """Check material quality test results."""
        pass_rate = data.get("material_quality_pass_rate", 100)
        thresholds = RISK_RULE_THRESHOLDS[self.sector]["material_quality_pass_rate"]

        if pass_rate < thresholds["critical"]:
            return RuleResult(
                rule_id="infra_material_fail",
                rule_name="Material Quality Issues",
                triggered=True,
                score_contribution=20,
                message=f"Material quality pass rate {pass_rate}%",
                severity=AlertSeverity.ERROR,
                data={"pass_rate": pass_rate, "threshold": thresholds["critical"]},
            )
        if pass_rate < thresholds["warning"]:
            return RuleResult(
                rule_id="infra_material_warning",
                rule_name="Material Quality Warning",
                triggered=True,
                score_contribution=10,
                message=f"Material quality pass rate {pass_rate}% requires review",
                severity=AlertSeverity.WARNING,
                data={"pass_rate": pass_rate, "threshold": thresholds["warning"]},
            )

        return RuleResult(
            rule_id="infra_material_ok",
            rule_name="Material Quality",
            triggered=False,
            score_contribution=0,
            message=f"Material quality {pass_rate}%",
            severity=AlertSeverity.INFO,
            data={"pass_rate": pass_rate},
        )


# ============ RISK ASSESSMENT SERVICE ============


class RiskEngine:
    """
    Main risk assessment engine.

    Evaluates sector-specific rules and generates risk scores and alerts.
    """

    SECTOR_ENGINES = {
        SectorType.MINING: MiningRuleEngine,
        SectorType.CONSTRUCTION_INFRASTRUCTURE: InfrastructureRuleEngine,
        # Add further public sectors only with explicit, reviewed rule packs.
    }

    RISK_THRESHOLDS = {
        RiskLevel.LOW: 25,
        RiskLevel.MEDIUM: 50,
        RiskLevel.HIGH: 75,
        RiskLevel.CRITICAL: 100,
    }

    EVIDENCE_BOUNDS = {
        SectorType.MINING: {
            "tailings_level_pct": (0, 100, False),
            "terrain_displacement_mm": (0, None, False),
            "esg_score": (0, 100, False),
            "dust_concentration_ppm": (0, None, False),
            "water_quality_index": (0, 100, False),
            "extraction_efficiency_pct": (0, 100, False),
        },
        SectorType.CONSTRUCTION_INFRASTRUCTURE: {
            "structural_health_index": (0, 100, False),
            "timeline_delay_days": (0, None, False),
            "budget_overrun_pct": (0, None, False),
            "safety_incidents_30d": (0, None, True),
            "material_quality_pass_rate": (0, 100, False),
        },
    }

    def __init__(self):
        self.engines = {
            sector: engine_class()
            for sector, engine_class in self.SECTOR_ENGINES.items()
        }

    def _score_to_level(self, score: float) -> RiskLevel:
        """Convert numeric score to risk level."""
        if score >= 75:
            return RiskLevel.CRITICAL
        elif score >= 50:
            return RiskLevel.HIGH
        elif score >= 25:
            return RiskLevel.MEDIUM
        return RiskLevel.LOW

    def _generate_recommendations(
        self, sector: SectorType, triggered_rules: List[RuleResult]
    ) -> List[str]:
        """Generate recommendations based on triggered rules."""
        recommendations = []

        for rule in triggered_rules:
            if rule.severity == AlertSeverity.CRITICAL:
                recommendations.append(f"URGENT: Address {rule.rule_name} immediately")
            elif rule.severity == AlertSeverity.ERROR:
                recommendations.append(f"Review {rule.rule_name} within 24 hours")
            elif rule.severity == AlertSeverity.WARNING:
                recommendations.append(f"Monitor {rule.rule_name}")

        # Add sector-specific recommendations
        if sector == SectorType.MINING:
            if any(
                r.rule_id.startswith("mining_tailings") and r.triggered
                for r in triggered_rules
            ):
                recommendations.append("Schedule tailings capacity expansion review")
            if any(
                r.rule_id.startswith("mining_displacement") and r.triggered
                for r in triggered_rules
            ):
                recommendations.append("Conduct geotechnical stability assessment")

        elif sector == SectorType.CONSTRUCTION_INFRASTRUCTURE:
            if any(
                r.rule_id.startswith("infra_delay") and r.triggered
                for r in triggered_rules
            ):
                recommendations.append("Review critical path and resource allocation")
            if any(
                r.rule_id.startswith("infra_budget") and r.triggered
                for r in triggered_rules
            ):
                recommendations.append("Conduct cost variance analysis")

        return recommendations[:5]  # Limit to top 5

    def _generate_alerts(
        self, site_id: str, sector: SectorType, triggered_rules: List[RuleResult]
    ) -> List[RiskAlert]:
        """Generate alerts from triggered rules."""
        import uuid

        alerts = []

        for rule in triggered_rules:
            alert = RiskAlert(
                id=str(uuid.uuid4()),
                title=rule.rule_name,
                message=rule.message,
                severity=rule.severity,
                sector=sector,
                source="risk_engine",
                metric_name=rule.rule_id,
                metric_value=rule.data.get("value"),
                threshold=rule.data.get("threshold"),
                recommendation=None,
            )
            alerts.append(alert)

        return alerts

    def assess(
        self, site_id: str, sector: SectorType, data: Dict[str, Any]
    ) -> RiskAssessmentResult:
        """
        Run risk assessment for a site.

        Args:
            site_id: Site identifier
            sector: Sector type
            data: Sensor/metric data for evaluation

        Returns:
            Complete risk assessment result
        """
        import uuid

        # Get sector engine
        engine = self.engines.get(sector)
        if not engine:
            raise RiskEngineNotConfiguredError(
                f"Risk rules are not configured for sector: {sector.value}"
            )

        missing = [field for field in engine.required_fields if data.get(field) is None]
        if missing:
            raise RiskEvidenceError(
                "Risk assessment requires all rule-pack measurements; missing: "
                + ", ".join(missing)
            )
        invalid = [
            field
            for field in engine.required_fields
            if isinstance(data[field], bool)
            or not isinstance(data[field], (int, float))
            or not math.isfinite(float(data[field]))
        ]
        if invalid:
            raise RiskEvidenceError(
                "Risk assessment measurements must be finite numbers; invalid: "
                + ", ".join(invalid)
            )
        out_of_range: list[str] = []
        for metric_name, (minimum, maximum, integer_only) in self.EVIDENCE_BOUNDS[
            sector
        ].items():
            numeric_value = float(data[metric_name])
            if (
                numeric_value < minimum
                or (maximum is not None and numeric_value > maximum)
                or (integer_only and not numeric_value.is_integer())
            ):
                out_of_range.append(metric_name)
        if out_of_range:
            raise RiskEvidenceError(
                "Risk assessment measurements are outside their valid domain: "
                + ", ".join(out_of_range)
            )

        # Evaluate rules
        rule_results = engine.evaluate(data)
        triggered = [r for r in rule_results if r.triggered]

        # Calculate score (capped at 100)
        risk_score = min(100, sum(r.score_contribution for r in triggered))
        risk_level = self._score_to_level(risk_score)

        # Generate outputs
        alerts = self._generate_alerts(site_id, sector, triggered)
        recommendations = self._generate_recommendations(sector, triggered)

        return RiskAssessmentResult(
            assessment_id=str(uuid.uuid4()),
            site_id=site_id,
            sector=sector,
            risk_score=risk_score,
            risk_level=risk_level,
            triggered_rules=triggered,
            alerts=alerts,
            recommendations=recommendations,
            input_data=data,
        )


# Singleton instance
_risk_engine: Optional[RiskEngine] = None


def get_risk_engine() -> RiskEngine:
    """Get or create risk engine instance."""
    global _risk_engine
    if _risk_engine is None:
        _risk_engine = RiskEngine()
    return _risk_engine


# ============ PYDANTIC SCHEMAS FOR API ============


class RiskAssessmentRequest(BaseModel):
    """Request schema for risk assessment."""

    site_id: str
    sector: SectorType
    data: Dict[str, Any]


class RuleResultSchema(BaseModel):
    rule_id: str
    rule_name: str
    triggered: bool
    score_contribution: float
    message: str
    severity: str
    data: Dict[str, Any] = {}


class RiskAlertSchema(BaseModel):
    id: str
    title: str
    message: str
    severity: str
    sector: str
    source: str
    metric_name: Optional[str] = None
    metric_value: Optional[float] = None
    threshold: Optional[float] = None
    recommendation: Optional[str] = None
    created_at: datetime


class RiskAssessmentResponse(BaseModel):
    assessment_id: str
    site_id: str
    sector: str
    risk_score: float
    risk_level: str
    triggered_rules: List[RuleResultSchema]
    alerts: List[RiskAlertSchema]
    recommendations: List[str]
    assessed_at: datetime
