/// Angola's 2025 political-administrative division: 21 provinces and 326
/// municipalities. Source: Portal Oficial do Governo de Angola.
const angolaMunicipalities = <String, List<String>>{
  'Bengo': [
    'Ambriz',
    'Bula Atumba',
    'Dande',
    'Nambuangongo',
    'Pango Aluquém',
    'Quibaxe',
    'Muxaluando',
    'Piri',
    'Quicunzo',
    'Úcua',
    'Panguila',
    'Barra do Dande'
  ],
  'Benguela': [
    'Baía Farta',
    'Balombo',
    'Benguela',
    'Bocoio',
    'Caimbambo',
    'Catumbela',
    'Chongorói',
    'Cubal',
    'Ganda',
    'Lobito',
    'Egito Praia',
    'Chindumbo',
    'Dombe Grande',
    'Capupa',
    'Biópio',
    'Chila',
    'Chicuma',
    'Babaera',
    'Iambala',
    'Catengue',
    'Bolonguera',
    'Canhamela',
    'Navegantes'
  ],
  'Bié': [
    'Andulo',
    'Camacupa',
    'Catabola',
    'Chinguar',
    'Chitembo',
    'Cuemba',
    'Cunhinga',
    'Cuito',
    'Nharêa',
    'Luando',
    'Ringoma',
    'Mumbuê',
    'Calucinga',
    'Chicala',
    'Chipeta',
    'Umpulo',
    'Lúbia',
    'Cambândua',
    'Belo Horizonte'
  ],
  'Cabinda': [
    'Cabinda',
    'Cacongo',
    'Buco-Zau',
    'Belize',
    'Miconje',
    'Massabi',
    'Necuto',
    'Tando Zinze',
    'Liambo',
    'Ngoio'
  ],
  'Cuando': [
    'Cuito Cuanavale',
    'Dirico',
    'Mavinga',
    'Rivungo',
    'Xipundo',
    'Dima',
    'Luiana',
    'Mucusso',
    'Luengue'
  ],
  'Cuanza Norte': [
    'Ambaca',
    'Banga',
    'Bolongongo',
    'Cambambe',
    'Cazengo',
    'Golungo Alto',
    'Ngonguembo',
    'Lucala',
    'Quiculungo',
    'Samba Cajú',
    'Massangano',
    'Cêrca',
    'Tango',
    'Terreiro',
    'Aldeia Nova',
    'Caculo Cabaça',
    'Luinga'
  ],
  'Cuanza Sul': [
    'Gabela',
    'Cassongue',
    'Conda',
    'Ebo',
    'Mussende',
    'Porto Amboim',
    'Quilenda',
    'Quibala',
    'Seles',
    'Sumbe',
    'Waku Kungo',
    'Calulo',
    'Quirimbo',
    'Munenga',
    'Quissongo',
    'Gungo',
    'Sanga',
    'Gangula',
    'Pambangala',
    'Condé',
    'Amboiva',
    'Lonhe',
    'Quenha',
    'Boa Entrada'
  ],
  'Cubango': [
    'Menongue',
    'Cutato',
    'Cuchi',
    'Longa',
    'Chinguanja',
    'Caiundo',
    'Savate',
    'Cuangar',
    'Calai',
    'Mavengue',
    'Nancova'
  ],
  'Cunene': [
    'Cahama',
    'Cuanhama',
    'Curoca',
    'Cuvelai',
    'Namacunde',
    'Ombadja',
    'Chiéde',
    'Nehone',
    'Humbe',
    'Mupa',
    'Naulila',
    'Chitado',
    'Cafima',
    'Chissuata'
  ],
  'Huambo': [
    'Longonjo',
    'Bailundo',
    'Chicala Choloanga',
    'Mungo',
    'Chinjenje',
    'Ucuma',
    'Cachiungo',
    'Caála',
    'Ecunha',
    'Huambo',
    'Londuimbali',
    'Bimbe',
    'Sambo',
    'Galanga',
    'Alto Hama',
    'Chilata',
    'Cuima'
  ],
  'Huíla': [
    'Caconda',
    'Cacula',
    'Caluquembe',
    'Gambos',
    'Chibia',
    'Chicomba',
    'Chipindo',
    'Cuvango',
    'Humpata',
    'Lubango',
    'Matala',
    'Quilengues',
    'Quipungo',
    'Jamba Mineira',
    'Dongo',
    'Hoque',
    'Capelongo',
    'Chituto',
    'Capunda Cavilongo',
    'Viti Vivali',
    'Galangue',
    'Palanca',
    'Chicungo'
  ],
  'Icolo e Bengo': [
    'Sequele',
    'Cabo Ledo',
    'Bom Jesus',
    'Cabiri',
    'Catete',
    'Calumbo',
    'Quiçama'
  ],
  'Luanda': [
    'Luanda',
    'Cacuaco',
    'Cazenga',
    'Viana',
    'Belas',
    'Talatona',
    'Mussulo',
    'Sambizanga',
    'Rangel',
    'Maianga',
    'Samba',
    'Camama',
    'Mulenvos',
    'Kilamba',
    'Hoji Ya Henda',
    'Ingombota'
  ],
  'Lunda Norte': [
    'Cambulo',
    'Capenda Camulemba',
    'Caungula',
    'Chitato',
    'Cuango',
    'Cuílo',
    'Lubalo',
    'Lucapa',
    'Lóvua',
    'Xá-Muteba',
    'Dundo',
    'Xá Cassau',
    'Camaxilo',
    'Luangue',
    'Luremo',
    'Canzar',
    'Cassanje Calucala',
    'Mussungue',
    'Cafunfu'
  ],
  'Lunda Sul': [
    'Cacolo',
    'Dala',
    'Muconda',
    'Saurimo',
    'Chiluage',
    'Cassai-Sul',
    'Xassengue',
    'Alto Chicapa',
    'Sombo',
    'Muriege',
    'Luma Cassai',
    'Cazage',
    'Muangueji',
    'Cassengo'
  ],
  'Malanje': [
    'Cacuso',
    'Cahombo',
    'Calandula',
    'Cambundi Catembo',
    'Cangandala',
    'Kunda dya Baze',
    'Luquembo',
    'Malanje',
    'Marimba',
    'Massango',
    'Quela',
    'Quirima',
    'Kiwaba Nzoji',
    'Cateco Cangola',
    'Cuale',
    'Pungo A Ndongo',
    'Ngola Luiji',
    'Quihuhu',
    'Xandel',
    'Cambo Suinginge',
    'Milando',
    'Quitapa',
    'Capunda',
    'Muquixe',
    'Quêssua',
    'Caculama',
    'Mbanji Ya Ngola'
  ],
  'Moxico': [
    'Camanongue',
    'Léua',
    'Chiúme',
    'Lumbala Nguimbo',
    'Alto Cuito',
    'Lutembo',
    'Cangumbe',
    'Luena',
    'Cangamba',
    'Lucusse',
    'Ninda',
    'Lutuai'
  ],
  'Moxico Leste': [
    'Cazombo',
    'Luacano',
    'Cameia',
    'Luau',
    'Nana Candundo',
    'Macondo',
    'Caianda',
    'Lóvua do Zambeze',
    'Lago Dilolo'
  ],
  'Namibe': [
    'Moçâmedes',
    'Camucuio',
    'Bibala',
    'Virei',
    'Tômbua',
    'Lucira',
    'Iona',
    'Sacomar',
    'Cacimbas'
  ],
  'Uíge': [
    'Uíge',
    'Ambuíla',
    'Bembe',
    'Bungo',
    'Milunga',
    'Damba',
    'Maquela do Zombo',
    'Mucaba',
    'Negage',
    'Puri',
    'Quimbele',
    'Sanza Pombo',
    'Songo',
    'Cangola',
    'Nova Esperança',
    'Dange Quitexe',
    'Sacandica',
    'Nsosso',
    'Lucunga',
    'Quipedro',
    'Massau',
    'Vista Alegre',
    'Alto Zaza'
  ],
  'Zaire': [
    'Mbanza Kongo',
    'Soyo',
    'Nzeto',
    'Cuimba',
    'Nóqui',
    'Tomboco',
    'Luvo',
    'Lufico',
    'Quêlo',
    'Serra de Canda',
    'Quindeje'
  ],
};
