"""Canonical password helpers compatible with existing stored hashes."""

import base64
import bcrypt
import hashlib
import hmac


PASSWORD_MIN_CHARACTERS = 6
ADMIN_PASSWORD_MIN_CHARACTERS = 12
PASSWORD_MAX_BYTES = 72


def validate_password_byte_length(password: str) -> str:
    """Reject values bcrypt would otherwise silently truncate."""

    if len(password.encode("utf-8")) > PASSWORD_MAX_BYTES:
        raise ValueError(
            f"password must not exceed {PASSWORD_MAX_BYTES} UTF-8 bytes"
        )
    return password


def validate_new_password(password: str) -> str:
    """Validate credentials before bcrypt can truncate their UTF-8 bytes."""

    if len(password) < PASSWORD_MIN_CHARACTERS:
        raise ValueError(
            f"password must contain at least {PASSWORD_MIN_CHARACTERS} characters"
        )
    return validate_password_byte_length(password)


def validate_admin_password(password: str) -> str:
    """Apply the stronger bootstrap policy for privileged seed accounts."""

    if len(password) < ADMIN_PASSWORD_MIN_CHARACTERS:
        raise ValueError(
            "admin password must contain at least "
            f"{ADMIN_PASSWORD_MIN_CHARACTERS} characters"
        )
    return validate_password_byte_length(password)


def _password_bytes(password: str | None) -> bytes:
    """Match bcrypt's historical 72-byte password handling."""

    return (password or "").encode("utf-8")[:72]


def hash_password(password: str) -> str:
    """Create a bcrypt hash compatible with hashes generated by passlib."""

    return bcrypt.hashpw(_password_bytes(password), bcrypt.gensalt()).decode("ascii")


def _is_legacy_sha256(s: str) -> bool:
    """Rudimentary check whether a stored hash looks like a SHA256 hex digest."""
    if not s or not isinstance(s, str):
        return False
    return len(s) == 64 and all(c in "0123456789abcdef" for c in s.lower())


def _ab64_decode(value: str) -> bytes:
    """Decode passlib's adapted Base64 representation."""

    normalized = value.replace(".", "+")
    normalized += "=" * (-len(normalized) % 4)
    return base64.b64decode(normalized)


def _verify_legacy_pbkdf2(password: str, encoded: str) -> bool:
    """Verify passlib ``pbkdf2_sha256`` hashes already stored in the DB."""

    try:
        _, scheme, rounds_raw, salt_raw, checksum_raw = encoded.split("$")
        if scheme != "pbkdf2-sha256":
            return False
        rounds = int(rounds_raw)
        if rounds <= 0:
            return False
        salt = _ab64_decode(salt_raw)
        expected = _ab64_decode(checksum_raw)
        actual = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, rounds)
        return hmac.compare_digest(actual, expected)
    except (TypeError, ValueError):
        return False


def verify_password(plain_password: str, hashed_password: str) -> bool:
    """Verify a plaintext password against either a bcrypt or legacy SHA256 hash.

    Supports bcrypt, passlib PBKDF2-SHA256, and the oldest SHA256 digests.
    """
    if not hashed_password:
        return False
    try:
        if hashed_password.startswith("$2"):
            return bcrypt.checkpw(_password_bytes(plain_password), hashed_password.encode("ascii"))
        if hashed_password.startswith("$pbkdf2-sha256$"):
            return _verify_legacy_pbkdf2(plain_password, hashed_password)
        if _is_legacy_sha256(hashed_password):
            sha = hashlib.sha256(plain_password.encode("utf-8")).hexdigest()
            return hmac.compare_digest(sha, hashed_password)
        return False
    except Exception:
        return False
